// 2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
using System;
using System.Numerics;

internal class EvenFibonacciNumbers
{
    private static void Main()
    {
        BigInteger fibonacciZero = 0;
        BigInteger fibonacciOne = 1;
        BigInteger sum = 0;
        int sequenceLength = 35;
        for (int i = 0; i < sequenceLength + 2; i++)
        {
            if (fibonacciZero % 2 == 0 && fibonacciZero <= 4000000)
            {
                sum += fibonacciZero;
            }

            fibonacciZero += fibonacciOne;
            fibonacciOne = fibonacciZero - fibonacciOne;
        }

        Console.WriteLine(sum); // 4613732
    }
}